//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.25 at 11:08:17 PM BRST 
//


package br.edu.unisinos.pgr.lcenteleghe.tmx;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tileMap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tileMap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Imagelayer }
     * 
     */
    public Imagelayer createImagelayer() {
        return new Imagelayer();
    }

    /**
     * Create an instance of {@link Tileset }
     * 
     */
    public Tileset createTileset() {
        return new Tileset();
    }

    /**
     * Create an instance of {@link Objectgroup }
     * 
     */
    public Objectgroup createObjectgroup() {
        return new Objectgroup();
    }

    /**
     * Create an instance of {@link Layer }
     * 
     */
    public Layer createLayer() {
        return new Layer();
    }

    /**
     * Create an instance of {@link Layer.Data }
     * 
     */
    public Layer.Data createLayerData() {
        return new Layer.Data();
    }

    /**
     * Create an instance of {@link Tileset.Terraintypes }
     * 
     */
    public Tileset.Terraintypes createTilesetTerraintypes() {
        return new Tileset.Terraintypes();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Imagelayer.Image }
     * 
     */
    public Imagelayer.Image createImagelayerImage() {
        return new Imagelayer.Image();
    }

    /**
     * Create an instance of {@link Tileset.Tileoffset }
     * 
     */
    public Tileset.Tileoffset createTilesetTileoffset() {
        return new Tileset.Tileoffset();
    }

    /**
     * Create an instance of {@link Tileset.Image }
     * 
     */
    public Tileset.Image createTilesetImage() {
        return new Tileset.Image();
    }

    /**
     * Create an instance of {@link Tileset.Tile }
     * 
     */
    public Tileset.Tile createTilesetTile() {
        return new Tileset.Tile();
    }

    /**
     * Create an instance of {@link Objectgroup.Object }
     * 
     */
    public Objectgroup.Object createObjectgroupObject() {
        return new Objectgroup.Object();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Layer.Data.Tile }
     * 
     */
    public Layer.Data.Tile createLayerDataTile() {
        return new Layer.Data.Tile();
    }

    /**
     * Create an instance of {@link Tileset.Terraintypes.Terrain }
     * 
     */
    public Tileset.Terraintypes.Terrain createTilesetTerraintypesTerrain() {
        return new Tileset.Terraintypes.Terrain();
    }

}
